// This file is autogenerated by VESC Tool

#ifndef NYX_CONFXML_H_
#define NYX_CONFXML_H_

#include <stdint.h>
#include <stdbool.h>

// Constants
#define DATA_NYX_LIGHTING_CONFIG__SIZE		2074

// Variables
extern uint8_t data_nyx_lighting_config_[];

// NYX_CONFXML_H
#endif
