// This file is autogenerated by tools/generate_nyx_main_config.py

#ifndef NYX_MAIN_CONFXML_H_
#define NYX_MAIN_CONFXML_H_

#include <stdint.h>
#include <stdbool.h>

#define DATA_MAIN_CONFIG_T__SIZE        5452
extern uint8_t data_main_config_t_[];

#endif
