// This file is autogenerated by tools/generate_nyx_main_config.py

#ifndef NYX_MAIN_CONFPARSER_H_
#define NYX_MAIN_CONFPARSER_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

#define MAIN_CONFIG_T_SIGNATURE        2597225484

int32_t nyx_main_confparser_serialize_main_config_t(uint8_t *buffer, const main_config_t *conf);
bool nyx_main_confparser_deserialize_main_config_t(const uint8_t *buffer, main_config_t *conf);
void nyx_main_confparser_set_defaults_main_config_t(main_config_t *conf);

#endif
