// This file is autogenerated by VESC Tool

#ifndef NYX_CONFPARSER_H_
#define NYX_CONFPARSER_H_

#include "../nyx_lighting.h"
#include <stdint.h>
#include <stdbool.h>

// Constants
#define NYX_LIGHTING_CONFIG_SIGNATURE		939684651
#define SERIALIZED_CONFIG_LENGTH	29

// Functions
int32_t confparser_serialize_nyx_lighting_config(uint8_t *buffer, const nyx_lighting_config *conf);
bool confparser_deserialize_nyx_lighting_config(const uint8_t *buffer, nyx_lighting_config *conf);
void confparser_set_defaults_nyx_lighting_config(nyx_lighting_config *conf);

// NYX_CONFPARSER_H
#endif
