// This file is autogenerated by VESC Tool

#include <string.h>
#include "buffer.h"
#include "nyx_conf_default.h"
#include "nyx_confparser.h"

int32_t confparser_serialize_nyx_lighting_config(uint8_t *buffer, const nyx_lighting_config *conf) {
	int32_t ind = 0;

	buffer_append_uint32(buffer, NYX_LIGHTING_CONFIG_SIGNATURE, &ind);

	buffer[ind++] = conf->effect;
	buffer_append_uint16(buffer, conf->led_count, &ind);
	buffer_append_float16(buffer, conf->brightness, 1000, &ind);
	buffer_append_float16(buffer, conf->speed, 100, &ind);
	buffer[ind++] = conf->enabled;
	buffer[ind++] = conf->auto_start;
	buffer_append_uint16(buffer, conf->red, &ind);
	buffer_append_uint16(buffer, conf->green, &ind);
	buffer_append_uint16(buffer, conf->blue, &ind);
	buffer[ind++] = conf->brake_enabled;
	buffer_append_uint16(buffer, conf->brake_can_id, &ind);
	buffer_append_float16(buffer, conf->brake_adc_threshold, 1000, &ind);
	buffer[ind++] = conf->brake_active_high;
	buffer_append_float16(buffer, conf->brake_brightness, 1000, &ind);
	buffer_append_float16(buffer, conf->brake_blink_hz, 100, &ind);

	return ind;
}

bool confparser_deserialize_nyx_lighting_config(const uint8_t *buffer, nyx_lighting_config *conf) {
	int32_t ind = 0;

	uint32_t signature = buffer_get_uint32(buffer, &ind);
	if (signature != NYX_LIGHTING_CONFIG_SIGNATURE) {
		return false;
	}

	conf->effect = buffer[ind++];
	conf->led_count = buffer_get_uint16(buffer, &ind);
	conf->brightness = buffer_get_float16(buffer, 1000, &ind);
	conf->speed = buffer_get_float16(buffer, 100, &ind);
	conf->enabled = buffer[ind++];
	conf->auto_start = buffer[ind++];
	conf->red = buffer_get_uint16(buffer, &ind);
	conf->green = buffer_get_uint16(buffer, &ind);
	conf->blue = buffer_get_uint16(buffer, &ind);
	conf->brake_enabled = buffer[ind++];
	conf->brake_can_id = buffer_get_uint16(buffer, &ind);
	conf->brake_adc_threshold = buffer_get_float16(buffer, 1000, &ind);
	conf->brake_active_high = buffer[ind++];
	conf->brake_brightness = buffer_get_float16(buffer, 1000, &ind);
	conf->brake_blink_hz = buffer_get_float16(buffer, 100, &ind);

	return true;
}

void confparser_set_defaults_nyx_lighting_config(nyx_lighting_config *conf) {
	conf->effect = NYX_LIGHTING_DEFAULT_EFFECT;
	conf->led_count = NYX_LIGHTING_DEFAULT_LED_COUNT;
	conf->brightness = NYX_LIGHTING_DEFAULT_BRIGHTNESS;
	conf->speed = NYX_LIGHTING_DEFAULT_SPEED;
	conf->enabled = NYX_LIGHTING_DEFAULT_ENABLED;
	conf->auto_start = NYX_LIGHTING_DEFAULT_AUTO_START;
	conf->red = NYX_LIGHTING_DEFAULT_RED;
	conf->green = NYX_LIGHTING_DEFAULT_GREEN;
	conf->blue = NYX_LIGHTING_DEFAULT_BLUE;
	conf->brake_enabled = NYX_LIGHTING_DEFAULT_BRAKE_ENABLED;
	conf->brake_can_id = NYX_LIGHTING_DEFAULT_BRAKE_CAN_ID;
	conf->brake_adc_threshold = NYX_LIGHTING_DEFAULT_BRAKE_ADC_THRESHOLD;
	conf->brake_active_high = NYX_LIGHTING_DEFAULT_BRAKE_ACTIVE_HIGH;
	conf->brake_brightness = NYX_LIGHTING_DEFAULT_BRAKE_BRIGHTNESS;
	conf->brake_blink_hz = NYX_LIGHTING_DEFAULT_BRAKE_BLINK_HZ;
}
