// This file is autogenerated by tools/generate_nyx_main_config.py

#include <string.h>
#include "buffer.h"
#include "conf_general.h"
#include "nyx_main_confparser.h"

int32_t nyx_main_confparser_serialize_main_config_t(uint8_t *buffer, const main_config_t *conf) {
	int32_t ind = 0;
	buffer_append_uint32(buffer, MAIN_CONFIG_T_SIGNATURE, &ind);
	buffer_append_int16(buffer, conf->controller_id, &ind);
	buffer[ind++] = conf->can_baud_rate;
	buffer_append_int16(buffer, conf->can_status_rate_hz, &ind);
	buffer[ind++] = conf->wifi_mode;
	strcpy((char*)buffer + ind, conf->wifi_sta_ssid);
	ind += strlen(conf->wifi_sta_ssid) + 1;
	strcpy((char*)buffer + ind, conf->wifi_sta_key);
	ind += strlen(conf->wifi_sta_key) + 1;
	strcpy((char*)buffer + ind, conf->wifi_ap_ssid);
	ind += strlen(conf->wifi_ap_ssid) + 1;
	strcpy((char*)buffer + ind, conf->wifi_ap_key);
	ind += strlen(conf->wifi_ap_key) + 1;
	buffer[ind++] = conf->use_tcp_local;
	buffer[ind++] = conf->use_tcp_hub;
	strcpy((char*)buffer + ind, conf->tcp_hub_url);
	ind += strlen(conf->tcp_hub_url) + 1;
	buffer_append_uint16(buffer, conf->tcp_hub_port, &ind);
	strcpy((char*)buffer + ind, conf->tcp_hub_id);
	ind += strlen(conf->tcp_hub_id) + 1;
	strcpy((char*)buffer + ind, conf->tcp_hub_pass);
	ind += strlen(conf->tcp_hub_pass) + 1;
	buffer[ind++] = conf->ble_mode;
	strcpy((char*)buffer + ind, conf->ble_name);
	ind += strlen(conf->ble_name) + 1;
	buffer_append_uint32(buffer, conf->ble_pin, &ind);
	buffer_append_uint32(buffer, conf->ble_service_capacity, &ind);
	buffer_append_uint32(buffer, conf->ble_chr_descr_capacity, &ind);
	buffer[ind++] = conf->lighting_enabled;
	buffer[ind++] = conf->lighting_effect;
	buffer[ind++] = conf->lighting_color;
	buffer[ind++] = conf->lighting_palette;
	buffer_append_uint16(buffer, conf->lighting_led_count, &ind);
	buffer_append_float16(buffer, conf->lighting_brightness, 1000, &ind);
	buffer_append_float16(buffer, conf->lighting_speed, 100, &ind);
	buffer[ind++] = conf->lighting_auto_start;
	buffer_append_uint16(buffer, conf->lighting_red, &ind);
	buffer_append_uint16(buffer, conf->lighting_green, &ind);
	buffer_append_uint16(buffer, conf->lighting_blue, &ind);
	buffer[ind++] = conf->brake_enabled;
	buffer_append_uint16(buffer, conf->brake_can_id, &ind);
	buffer_append_float16(buffer, conf->brake_adc_threshold, 1000, &ind);
	buffer[ind++] = conf->brake_active_high;
	buffer_append_float16(buffer, conf->brake_brightness, 1000, &ind);
	buffer_append_float16(buffer, conf->brake_blink_hz, 100, &ind);
	buffer[ind++] = conf->brake_color;
	buffer_append_uint16(buffer, conf->brake_red, &ind);
	buffer_append_uint16(buffer, conf->brake_green, &ind);
	buffer_append_uint16(buffer, conf->brake_blue, &ind);
	return ind;
}

bool nyx_main_confparser_deserialize_main_config_t(const uint8_t *buffer, main_config_t *conf) {
	int32_t ind = 0;
	uint32_t signature = buffer_get_uint32(buffer, &ind);
	if (signature != MAIN_CONFIG_T_SIGNATURE) return false;
	conf->controller_id = buffer_get_int16(buffer, &ind);
	conf->can_baud_rate = buffer[ind++];
	conf->can_status_rate_hz = buffer_get_int16(buffer, &ind);
	conf->wifi_mode = buffer[ind++];
	strcpy(conf->wifi_sta_ssid, (char*)buffer + ind);
	ind += strlen(conf->wifi_sta_ssid) + 1;
	strcpy(conf->wifi_sta_key, (char*)buffer + ind);
	ind += strlen(conf->wifi_sta_key) + 1;
	strcpy(conf->wifi_ap_ssid, (char*)buffer + ind);
	ind += strlen(conf->wifi_ap_ssid) + 1;
	strcpy(conf->wifi_ap_key, (char*)buffer + ind);
	ind += strlen(conf->wifi_ap_key) + 1;
	conf->use_tcp_local = buffer[ind++];
	conf->use_tcp_hub = buffer[ind++];
	strcpy(conf->tcp_hub_url, (char*)buffer + ind);
	ind += strlen(conf->tcp_hub_url) + 1;
	conf->tcp_hub_port = buffer_get_uint16(buffer, &ind);
	strcpy(conf->tcp_hub_id, (char*)buffer + ind);
	ind += strlen(conf->tcp_hub_id) + 1;
	strcpy(conf->tcp_hub_pass, (char*)buffer + ind);
	ind += strlen(conf->tcp_hub_pass) + 1;
	conf->ble_mode = buffer[ind++];
	strcpy(conf->ble_name, (char*)buffer + ind);
	ind += strlen(conf->ble_name) + 1;
	conf->ble_pin = buffer_get_uint32(buffer, &ind);
	conf->ble_service_capacity = buffer_get_uint32(buffer, &ind);
	conf->ble_chr_descr_capacity = buffer_get_uint32(buffer, &ind);
	conf->lighting_enabled = buffer[ind++];
	conf->lighting_effect = buffer[ind++];
	conf->lighting_color = buffer[ind++];
	conf->lighting_palette = buffer[ind++];
	conf->lighting_led_count = buffer_get_uint16(buffer, &ind);
	conf->lighting_brightness = buffer_get_float16(buffer, 1000, &ind);
	conf->lighting_speed = buffer_get_float16(buffer, 100, &ind);
	conf->lighting_auto_start = buffer[ind++];
	conf->lighting_red = buffer_get_uint16(buffer, &ind);
	conf->lighting_green = buffer_get_uint16(buffer, &ind);
	conf->lighting_blue = buffer_get_uint16(buffer, &ind);
	conf->brake_enabled = buffer[ind++];
	conf->brake_can_id = buffer_get_uint16(buffer, &ind);
	conf->brake_adc_threshold = buffer_get_float16(buffer, 1000, &ind);
	conf->brake_active_high = buffer[ind++];
	conf->brake_brightness = buffer_get_float16(buffer, 1000, &ind);
	conf->brake_blink_hz = buffer_get_float16(buffer, 100, &ind);
	conf->brake_color = buffer[ind++];
	conf->brake_red = buffer_get_uint16(buffer, &ind);
	conf->brake_green = buffer_get_uint16(buffer, &ind);
	conf->brake_blue = buffer_get_uint16(buffer, &ind);
	return true;
}

void nyx_main_confparser_set_defaults_main_config_t(main_config_t *conf) {
	conf->controller_id = HW_DEFAULT_ID;
	conf->can_baud_rate = CONF_CAN_BAUD_RATE;
	conf->can_status_rate_hz = CONF_CAN_STATUS_RATE_HZ;
	conf->wifi_mode = CONF_WIFI_MODE;
	strcpy(conf->wifi_sta_ssid, CONF_WIFI_STA_SSID);
	strcpy(conf->wifi_sta_key, CONF_WIFI_STA_KEY);
	strcpy(conf->wifi_ap_ssid, CONF_WIFI_AP_SSID);
	strcpy(conf->wifi_ap_key, CONF_WIFI_AP_KEY);
	conf->use_tcp_local = CONF_USE_TCP_LOCAL;
	conf->use_tcp_hub = CONF_USE_TCP_HUB;
	strcpy(conf->tcp_hub_url, CONF_TCP_HUB_URL);
	conf->tcp_hub_port = CONF_TCP_HUB_PORT;
	strcpy(conf->tcp_hub_id, CONF_TCP_HUB_ID);
	strcpy(conf->tcp_hub_pass, CONF_TCP_HUB_PASS);
	conf->ble_mode = CONF_BLE_MODE;
	strcpy(conf->ble_name, CONF_BLE_NAME);
	conf->ble_pin = CONF_BLE_PIN;
	conf->ble_service_capacity = CONF_BLE_SERVICE_CAPACITY;
	conf->ble_chr_descr_capacity = CONF_BLE_CHR_DESCR_CAPACITY;
	conf->lighting_enabled = NYX_LIGHTING_DEFAULT_ENABLED;
	conf->lighting_effect = NYX_LIGHTING_DEFAULT_EFFECT;
	conf->lighting_color = NYX_LIGHTING_DEFAULT_COLOR;
	conf->lighting_palette = NYX_LIGHTING_DEFAULT_PALETTE;
	conf->lighting_led_count = NYX_LIGHTING_DEFAULT_LED_COUNT;
	conf->lighting_brightness = NYX_LIGHTING_DEFAULT_BRIGHTNESS;
	conf->lighting_speed = NYX_LIGHTING_DEFAULT_SPEED;
	conf->lighting_auto_start = NYX_LIGHTING_DEFAULT_AUTO_START;
	conf->lighting_red = NYX_LIGHTING_DEFAULT_RED;
	conf->lighting_green = NYX_LIGHTING_DEFAULT_GREEN;
	conf->lighting_blue = NYX_LIGHTING_DEFAULT_BLUE;
	conf->brake_enabled = NYX_LIGHTING_DEFAULT_BRAKE_ENABLED;
	conf->brake_can_id = NYX_LIGHTING_DEFAULT_BRAKE_CAN_ID;
	conf->brake_adc_threshold = NYX_LIGHTING_DEFAULT_BRAKE_ADC_THRESHOLD;
	conf->brake_active_high = NYX_LIGHTING_DEFAULT_BRAKE_ACTIVE_HIGH;
	conf->brake_brightness = NYX_LIGHTING_DEFAULT_BRAKE_BRIGHTNESS;
	conf->brake_blink_hz = NYX_LIGHTING_DEFAULT_BRAKE_BLINK_HZ;
	conf->brake_color = NYX_BRAKE_DEFAULT_COLOR;
	conf->brake_red = NYX_BRAKE_DEFAULT_RED;
	conf->brake_green = NYX_BRAKE_DEFAULT_GREEN;
	conf->brake_blue = NYX_BRAKE_DEFAULT_BLUE;
}
