import re
import struct
import xml.etree.ElementTree as ET
import zlib


XML_PATH = "main/config/settings.xml"
OUT_DIR = "main/hwconf"


def crc32c(text):
    crc = 0xffffffff
    for ch in text:
        crc ^= ord(ch)
        for _ in range(8):
            crc = (crc >> 1) ^ (0x82f63b78 if crc & 1 else 0)
    return (~crc) & 0xffffffff


def c_array(data):
    rows = []
    for i in range(0, len(data), 16):
        rows.append("\t" + ", ".join("0x%02x" % b for b in bytearray(data[i:i + 16])) + ", ")
    return "\n".join(rows)


def main():
    root = ET.parse(XML_PATH).getroot()
    params = root.find("Params")
    serial = [x.text for x in root.find("SerOrder")]
    signature_text = ""
    for name in serial:
        p = params.find(name)
        signature_text += name + str(int(p.findtext("type", "0"))) + str(int(p.findtext("vTx", "0")))
        signature_text += "".join(x.text or "" for x in p.findall("enumNames"))
    signature = crc32c(signature_text)

    parser_h = '''// This file is autogenerated by tools/generate_nyx_main_config.py

#ifndef NYX_MAIN_CONFPARSER_H_
#define NYX_MAIN_CONFPARSER_H_

#include "datatypes.h"
#include <stdint.h>
#include <stdbool.h>

#define MAIN_CONFIG_T_SIGNATURE        %d

int32_t nyx_main_confparser_serialize_main_config_t(uint8_t *buffer, const main_config_t *conf);
bool nyx_main_confparser_deserialize_main_config_t(const uint8_t *buffer, main_config_t *conf);
void nyx_main_confparser_set_defaults_main_config_t(main_config_t *conf);

#endif
''' % signature

    def serialize_line(name, p):
        typ = int(p.findtext("type", "0"))
        tx = int(p.findtext("vTx", "0"))
        if typ in (4, 5, 6):
            return "\tbuffer[ind++] = conf->%s;" % name
        if typ == 2:
            return {
                1: "\tbuffer[ind++] = (uint8_t)conf->%s;" % name,
                2: "\tbuffer[ind++] = (uint8_t)conf->%s;" % name,
                3: "\tbuffer_append_uint16(buffer, conf->%s, &ind);" % name,
                4: "\tbuffer_append_int16(buffer, conf->%s, &ind);" % name,
                5: "\tbuffer_append_uint32(buffer, conf->%s, &ind);" % name,
                6: "\tbuffer_append_int32(buffer, conf->%s, &ind);" % name,
            }[tx]
        if typ == 1:
            scale = p.findtext("vTxDoubleScale", "1")
            return "\tbuffer_append_float16(buffer, conf->%s, %s, &ind);" % (name, scale)
        if typ == 3:
            return "\tstrcpy((char*)buffer + ind, conf->%s);\n\tind += strlen(conf->%s) + 1;" % (name, name)
        raise RuntimeError("unsupported type %s for %s" % (typ, name))

    def deserialize_line(name, p):
        typ = int(p.findtext("type", "0"))
        tx = int(p.findtext("vTx", "0"))
        if typ in (4, 5, 6):
            return "\tconf->%s = buffer[ind++];" % name
        if typ == 2:
            return {
                1: "\tconf->%s = buffer[ind++];" % name,
                2: "\tconf->%s = (int8_t)buffer[ind++];" % name,
                3: "\tconf->%s = buffer_get_uint16(buffer, &ind);" % name,
                4: "\tconf->%s = buffer_get_int16(buffer, &ind);" % name,
                5: "\tconf->%s = buffer_get_uint32(buffer, &ind);" % name,
                6: "\tconf->%s = buffer_get_int32(buffer, &ind);" % name,
            }[tx]
        if typ == 1:
            scale = p.findtext("vTxDoubleScale", "1")
            return "\tconf->%s = buffer_get_float16(buffer, %s, &ind);" % (name, scale)
        if typ == 3:
            return "\tstrcpy(conf->%s, (char*)buffer + ind);\n\tind += strlen(conf->%s) + 1;" % (name, name)
        raise RuntimeError("unsupported type %s for %s" % (typ, name))

    ser = "\n".join(serialize_line(n, params.find(n)) for n in serial)
    deser = "\n".join(deserialize_line(n, params.find(n)) for n in serial)
    defaults = []
    for name in serial:
        p = params.find(name)
        if name == "controller_id":
            defaults.append("\tconf->controller_id = HW_DEFAULT_ID;")
            continue
        define = p.findtext("cDefine", "")
        if not define:
            continue
        if int(p.findtext("type", "0")) == 3:
            defaults.append("\tstrcpy(conf->%s, %s);" % (name, define))
        else:
            defaults.append("\tconf->%s = %s;" % (name, define))

    parser_c = '''// This file is autogenerated by tools/generate_nyx_main_config.py

#include <string.h>
#include "buffer.h"
#include "conf_general.h"
#include "nyx_main_confparser.h"

int32_t nyx_main_confparser_serialize_main_config_t(uint8_t *buffer, const main_config_t *conf) {
\tint32_t ind = 0;
\tbuffer_append_uint32(buffer, MAIN_CONFIG_T_SIGNATURE, &ind);
%s
\treturn ind;
}

bool nyx_main_confparser_deserialize_main_config_t(const uint8_t *buffer, main_config_t *conf) {
\tint32_t ind = 0;
\tuint32_t signature = buffer_get_uint32(buffer, &ind);
\tif (signature != MAIN_CONFIG_T_SIGNATURE) return false;
%s
\treturn true;
}

void nyx_main_confparser_set_defaults_main_config_t(main_config_t *conf) {
%s
}
''' % (ser, deser, "\n".join(defaults))

    defaults_h = '''// This file is autogenerated by tools/generate_nyx_main_config.py

#ifndef NYX_MAIN_CONF_DEFAULT_H_
#define NYX_MAIN_CONF_DEFAULT_H_

'''
    for name in serial:
        p = params.find(name)
        if name == "controller_id":
            continue
        define = p.findtext("cDefine", "")
        if not define:
            continue
        typ = int(p.findtext("type", "0"))
        if typ == 3:
            val = '"%s"' % (p.findtext("valString", "") or "")
        elif typ == 1:
            val = p.findtext("valDouble", "0")
        else:
            val = p.findtext("valInt", "0")
        defaults_h += "#ifndef %s\n#define %s %s\n#endif\n\n" % (define, define, val)
    defaults_h += "#endif\n"

    xml = open(XML_PATH, "rb").read()
    compressed = struct.pack(">I", len(xml)) + zlib.compress(xml, 9)
    xml_h = '''// This file is autogenerated by tools/generate_nyx_main_config.py

#ifndef NYX_MAIN_CONFXML_H_
#define NYX_MAIN_CONFXML_H_

#include <stdint.h>
#include <stdbool.h>

#define DATA_MAIN_CONFIG_T__SIZE        %d
extern uint8_t data_main_config_t_[];

#endif
''' % len(compressed)
    xml_c = '''// This file is autogenerated by tools/generate_nyx_main_config.py

#include "nyx_main_confxml.h"

__attribute__((used)) uint8_t data_main_config_t_[%d] = {
%s
};
''' % (len(compressed), c_array(compressed))

    for name, content in {
        "nyx_main_confparser.h": parser_h,
        "nyx_main_confparser.c": parser_c,
        "nyx_main_conf_default.h": defaults_h,
        "nyx_main_confxml.h": xml_h,
        "nyx_main_confxml.c": xml_c,
    }.items():
        open(OUT_DIR + "/" + name, "wb").write(content.replace("\r\n", "\n").encode("utf-8"))
    print("signature=%d xml_bytes=%d" % (signature, len(compressed)))


if __name__ == "__main__":
    main()
